export const STR = {
  newGame: "새 게임",
  reset: "초기화",
  hint: "힌트",
  note: "메모",
  autoNotes: "메모 채우기",
  autoNotesShort: "자동메모",
  pause: "일시정지",
  pauseShort: "정지",
  resume: "재개",
  resumeShort: "계속",
  erase: "지우기",
  undo: "되돌리기",
  undoShort: "취소",
  redo: "다시실행",
  redoShort: "복구",
  difficulty: "난이도",
  easy: "쉬움",
  medium: "보통",
  hard: "어려움",
  score: "점수",
  mistakes: "실수",
  time: "시간",
  best: "최고 기록",
  paused: "일시정지됨",
  completed: "완료!",
  completedMsg: "스도쿠를 완성했습니다!",
  newRecord: "최고 기록 경신!",
  elapsedTime: "소요 시간",
  finalScore: "최종 점수",
  totalMistakes: "총 실수",
  hintsUsed: "힌트 사용",
  playAgain: "다시 하기",
  selectDifficulty: "난이도를 선택하세요",
  resetConfirm: "저장된 게임을 삭제하고 같은 난이도로 새 게임을 시작합니다.",
  newGameConfirm: "진행 중인 게임이 사라집니다. 새 게임을 시작할까요?",
  resetBtn: "초기화 및 새 게임",
  startBtn: "새 게임 시작",
  cancel: "취소",
  generating: "생성 중...",
  times: "회",
  failedTitle: "실수 3회",
  failedMsg: "실수 제한에 걸렸습니다. 이어서 풀거나 다시 시작할 수 있습니다.",
  keepPlaying: "제한 풀고 이어 풀기",
  retrySame: "같은 문제 다시",
  selectCellFirst: "먼저 칸을 선택하세요",
  nothingToUndo: "되돌릴 내용이 없습니다",
  hintOnFilled: "이미 채워진 칸입니다",
  autoNotesDone: "빈 칸에 후보 숫자를 채웠습니다",
} as const;
